settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: taisho
    path: .
    commands:
      build:
        status: true
        method: go build -o taisho ./cmd/taisho/main.go
      run:
        status: true
        method: ./taisho
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
