settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: taisho
  path: .
  commands:
    build:
      status: true
      method: go build -o app ./internal/main.go
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
