name: taisho-ci
on:
  push:
    branches:
      - master
env:
  IMAGE_ID: asia.gcr.io/${{secrets.GCP_PROJECT_ID}}/taisho
  IMAGE_TAG: latest
  GCP_RESION: asia-northeast1
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{secrets.GCP_PROJECT_ID}}
          service_account_key: ${{secrets.GCP_SERVICE_ACCOUNT}}
          export_default_credentials: true
      - name: configure Docker Registory
        run: gcloud auth configure-docker --quiet
      - name: Build Docker image
        run: docker build --no-cache -t ${IMAGE_ID}:${IMAGE_TAG} -f build/ci/Dockerfile .
      - name: Push Docker Registory
        run: docker push ${IMAGE_ID}
      - name: Deploy to Cloud Run
        run: gcloud run deploy taisho --image ${IMAGE_ID} --platform managed --region ${GCP_RESION}
